# Generated by Django 4.2.7 on 2023-11-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_description', models.TextField(blank=True)),
                ('client', models.CharField(max_length=255)),
                ('contractor', models.CharField(max_length=255)),
            ],
        ),
    ]
