# Generated by Django 4.2.7 on 2023-11-23 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('XYZ', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximum_x', models.IntegerField()),
                ('minimum_x', models.IntegerField()),
                ('maximum_y', models.IntegerField()),
                ('minimum_y', models.IntegerField()),
                ('maximum_z', models.IntegerField()),
                ('minimum_z', models.IntegerField()),
                ('basic_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XYZ.basicmodel')),
            ],
        ),
    ]
