# Generated by Django 4.2.7 on 2023-11-23 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('XYZ', '0002_inputmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('basic_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XYZ.basicmodel')),
            ],
        ),
    ]
