# Generated by Django 4.2.7 on 2023-11-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('XYZ', '0003_fileupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
