# Generated by Django 4.2.7 on 2023-11-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XYZ', '0004_delete_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputmodel',
            name='maximum_x',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inputmodel',
            name='maximum_y',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inputmodel',
            name='maximum_z',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inputmodel',
            name='minimum_x',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inputmodel',
            name='minimum_y',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inputmodel',
            name='minimum_z',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
